# Generated by Django 3.0.1 on 2020-05-31 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=31, unique=True)),
                ('real_name', models.CharField(max_length=61)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('emp_id',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz', models.CharField(max_length=61)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='activity.Employee')),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['emp_id'], name='activity_em_emp_id_9823fd_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeactivity',
            index=models.Index(fields=['employee', 'start_time', 'end_time'], name='activity_em_employe_83a920_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeactivity',
            unique_together={('employee', 'start_time', 'end_time')},
        ),
    ]
